- README.md
- contracts/HelloWorld.sol
> fix(readme.md): fix file path

- README.md
- contracts/HelloWorld.sol
- hardhat.config.js
- scripts/deploy.js
- test/Lock.js
- test/Lock.ts
> feat(helloworld.sol): add HelloWorld.sol

- README.md
- contracts/Counter.sol
> feat(counter.sol): add counter

- README.md
> docs(readme.md): fix list

- README.md
- contracts/Variables.sol
> feat(variables.sol): add Variables.sol

- README.md
- contracts/Constants.sol
> feat(constants.sol): add Constants.sol

- README.md
- contracts/Immutable.sol
> feat(immutable.sol): add Immutable.sol

- contracts/Constants.sol
- contracts/Immutable.sol
> docs(immutable.sol、Constants.sol): fix doc

- README.md
- contracts/SimpleStorage.sol
> feat(simplestorage.sol): add SimpleStorage.sol

- README.md
- contracts/EtherAndWei/EtherUnits.sol
> feat(etherunits.sol): add EtherUnits.sol

- README.md
- contracts/Time/Time.sol
> feat(time.sol): add Time.sol

- contracts/Immutable/Immutable.sol
> docs(immutable.sol): doc changes

- README.md
- contracts/GasAndGasPrice/Gas.sol
> feat(gas.sol): add Gas.sol

- contracts/HelloWorld/HelloWorld.md
- contracts/HelloWorld/HelloWorld.sol
- contracts/Preface/Preface.md
> docs(contracts/helloworld): doc changes

- README.md
- contracts/FirstApp/Counter.sol
- contracts/FirstApp/FirstApp.md
> docs(contracts/firstapp): doc changes

- README.md
- contracts/GasAndGasPrice/Gas.sol
- contracts/GasAndGasPrice/GasAndGasPrice.md
- contracts/Mapping/Mapping.md
- contracts/Mapping/Mapping.sol
- contracts/Mapping/NestedMapping.sol
- contracts/Time/Time.md
- contracts/Time/Time.sol
> docs(contracts/time): doc changes

- contracts/GasAndGasPrice/Gas.sol
- contracts/GasAndGasPrice/GasAndGasPrice.md
> docs(gasandgasprice): doc changes

- README.md
- contracts/EtherAndWei/EtherAndWei.md
- contracts/EtherAndWei/EtherUnits.sol
- contracts/GasAndGasPrice/Gas.sol
- contracts/GasAndGasPrice/GasAndGasPrice.md
> docs(etherandwei、gasandgasprice): doc changes

- README.md
- contracts/ReadAndWriteState/ReadAndWriteState.md
- contracts/ReadAndWriteState/SimpleStorage.sol
> docs(readandwritestate): doc changes

- README.md
- contracts/Constants/Constants.md
- contracts/Variables/Variables.md
- contracts/Variables/Variables.sol
> docs(variables): doc changes

- README.md
- contracts/Primitives/Primitives.md
- contracts/Primitives/Primitives.sol
> docs(primitives): doc changes

- contracts/Mapping/Mapping.md
- contracts/Mapping/Mapping.sol
- contracts/Mapping/NestedMapping.sol
- contracts/Primitives/Primitives.md
> docs(mapping): doc changes

- README.md
- contracts/EnumDemo/Enum.md
- contracts/EnumDemo/Enum.sol
- contracts/EnumDemo/EnumDeclaration.sol
- contracts/EnumDemo/EnumImport.sol
- contracts/GasAndGasPrice/GasAndGasPrice.md
- contracts/Mapping/Mapping.md
- contracts/Struct/Struct.md
- contracts/Struct/StructDeclaration.sol
- contracts/Struct/Todos.sol
- contracts/Struct/TodosStruct.sol
> feat(enum、struct): add enum、struct

- contracts/EnumDemo/Enum.md
> docs(enum): doc changes

- contracts/Struct/Struct.md
> docs(struct): doc changes

- contracts/ForAndWhile/ForAndWhile.md
- contracts/ForAndWhile/Loop.sol
- contracts/IfElse/IfElse.md
> feat(loop): add loop

- contracts/ForAndWhile/ForAndWhile.md
> docs(loop): fix character

- README.md
- contracts/Array/Array.sol
- contracts/Array/ArrayRemoveShifting.sol
- contracts/Array/ArrayReplaceFromEnd.sol
> feat(array): add array code

- README.md
- contracts/Array/ArrayReplaceFromEnd.sol
- contracts/DataLocations/DataLocations.sol
- contracts/FunctionInputOutputReturn/Function.sol
- contracts/String/String.sol
- hardhat.config.ts
> feat(contracts): add code

- contracts/FirstApp/FirstApp.md
- contracts/HelloWorld/HelloWorld.md
- contracts/Primitives/Primitives.md
- contracts/Variables/Variables.md
update Variables.md,FirstApp.md,Primitives.md and HelloWorld.md
> docs(variables.md): update Variables.md,FirstApp.md,Primitives.md and HelloWorld.md

- contracts/EtherAndWei/EtherAndWei.md
> docs(etherandwei.md): update EtherAndWei.md

- contracts/Time/Time.md
> docs(time.md): update Time.md

- contracts/EtherAndWei/EtherAndWei.md
> docs(etherandwei.md): add example url

- README.md
- contracts/GasAndGasPrice/GasAndGasPrice.md
> docs(gasandgasprice.md): update GasAndGasPrice.md

- contracts/FirstApp/Counter.sol
- contracts/FirstApp/FirstApp.md
> docs(firstapp.md): update firstapp.md

- Solidity/000.Preface/README.md
- Solidity/002.FirstApp/README.md
- Solidity/003.ValueType/README.md
- Solidity/004.Variables/README.md
- Solidity/005.Constants/README.md
- Solidity/006.Immutable/README.md
- Solidity/007.EtherUnits/README.md
- Solidity/008.TimeUnits/README.md
- Solidity/009.GasAndGasPrice/README.md
> feat(bg): add bg

- README.md
- Solidity/006.Immutable/Immutable.sol
- Solidity/006.Immutable/README.md
- Solidity/011.Structs/README.md
- Solidity/011.Structs/Todos.sol
fix some articles about content error
> docs(solidity): fix some articles about content error

- Solidity/003.ValueType/README.md
- Solidity/010.Mapping/README.md
- Solidity/011.Structs/README.md
> docs(solidity): fix content error

- Solidity/000.Preface/README.md
- Solidity/001.HelloWorld/README.md
> feat(arb): add arb

- Solidity/001.HelloWorld/README.md
- Solidity/002.FirstApp/README.md
> docs(002): review 002
